[build]
base = "client/"
publish = "client/build/"
command = "yarn build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context.staging.environment]
  REACT_APP_SERVER_URL = "https://shielded-tor-58261.herokuapp.com"